# Generated by Django 3.1.7 on 2022-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='duGioTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoTen', models.CharField(max_length=255)),
                ('toCM', models.CharField(max_length=50)),
                ('ngayDu', models.CharField(max_length=20)),
                ('phuChu', models.CharField(max_length=255)),
            ],
        ),
    ]
