# Generated by Django 3.1.7 on 2022-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duGio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KHDGTG_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoTen', models.CharField(max_length=255)),
                ('toCM', models.CharField(max_length=50)),
                ('ngayDay', models.CharField(max_length=20)),
                ('tenBai', models.CharField(max_length=255)),
                ('lop', models.CharField(max_length=5)),
                ('luotDu', models.CharField(max_length=2)),
                ('loai', models.CharField(max_length=5)),
                ('xepLoai', models.CharField(max_length=10)),
                ('phuChu', models.CharField(max_length=255)),
            ],
        ),
    ]
